name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LIBJXL_VERSION: 0.7.0
      LIBNSBMP_BUILDSYSTEM_VERSION: 1.10
      LIBNSBMP_VERSION: 0.1.7
      FLIF_VERSION: 0.4
    steps:
      - uses: actions/checkout@v4
      - name: Install tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential help2man cmake
          sudo apt-get install -y --no-install-recommends nettle-dev libargon2-dev libpng-dev libcharls-dev libavif-dev libheif-dev libtiff-dev libwebp-dev libopenjp2-7-dev libjxr-dev libzstd-dev liblzma-dev libbrotli-dev libbz2-dev zlib1g-dev libgtk-3-dev
      - name: Install libnsbmp
        run: |
          sudo mkdir /libnsbmp_build
          sudo chown chown $(whoami) /libnsbmp_build
          cd /libnsbmp_build
          wget https://download.netsurf-browser.org/libs/releases/buildsystem-${{env.LIBNSBMP_BUILDSYSTEM_VERSION}}.tar.gz
          tar -xf buildsystem-${{env.LIBNSBMP_BUILDSYSTEM_VERSION}}.tar.gz
          cd buildsystem-${{env.LIBNSBMP_BUILDSYSTEM_VERSION}}
          sudo make install PREFIX=/usr
          cd ..
          wget https://download.netsurf-browser.org/libs/releases/libnsbmp-${{env.LIBNSBMP_VERSION}}-src.tar.gz
          tar -xf libnsbmp-${{env.LIBNSBMP_VERSION}}-src.tar.gz
          cd libnsbmp-${{env.LIBNSBMP_VERSION}}
          make PREFIX=/usr COMPONENT_TYPE=lib-static
          sudo make install PREFIX=/usr COMPONENT_TYPE=lib-static
      - name: Install libjxl
        run: |
          sudo mkdir /libjxl_build
          sudo chown chown $(whoami) /libjxl_build
          cd /libjxl_build
          wget https://github.com/libjxl/libjxl/archive/refs/tags/v${{env.LIBJXL_VERSION}}.tar.gz
          tar -xf v${{env.LIBJXL_VERSION}}.tar.gz
          cd libjxl-${{env.LIBJXL_VERSION}}
          ./deps.sh
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTING=OFF -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_HWY=OFF -DJPEGXL_ENABLE_SKCMS=ON -DJPEGXL_BUNDLE_SKCMS=ON -DJPEGXL_ENABLE_TCMALLOC=OFF -DJPEGXL_ENABLE_TOOLS=OFF -DJPEGXL_ENABLE_SJPEG=OFF .
          make
          sudo make install
      - name: Install FLIF
        run: |
          sudo mkdir /flif_build
          sudo chown chown $(whoami) /flif_build
          cd /flif_build
          wget https://github.com/FLIF-hub/FLIF/archive/refs/tags/v${{env.FLIF_VERSION}}.tar.gz
          tar -xf v${{env.FLIF_VERSION}}.tar.gz
          cd FLIF-${{env.FLIF_VERSION}}
          make
          sudo make install PREFIX=/usr
          sudo make install-dev PREFIX=/usr
      - name: Build
        run: |
          cd ${{github.workspace}}
          make WITH_FLIF=1 WITH_JXRLIB=1
#      - uses: actions/upload-artifact@v4
#        with:
#          name: impack-debug
#          path: |
#            ${{github.workspace}}/impack
#            ${{github.workspace}}/impack-gtk
      - name: Run testsuite
        run: |
          cd ${{github.workspace}}
          make WITH_FLIF=1 WITH_JXRLIB=1 check
#      - uses: actions/upload-artifact@v4
#        with:
#          name: impack-testsuite-debug
#          path: ${{github.workspace}}/testsuite
